In [2]:
import pandas as pd
import matplotlib.pyplot as plt

PATH = "/home/harshil/IV-Surface-Reconstruction/src/data/spy_options_2010_2023_eod.csv"

In [3]:
data = pd.read_csv(PATH)
data.describe()

,Unnamed: 0,level_0,[QUOTE_UNIXTIME],[QUOTE_TIME_HOURS],[UNDERLYING_LAST],[EXPIRE_UNIX],[DTE],[C_DELTA],[C_GAMMA],[C_VEGA],...,[P_LAST],[P_DELTA],[P_GAMMA],[P_VEGA],[P_THETA],[P_RHO],[P_IV],[P_VOLUME],[STRIKE_DISTANCE],[STRIKE_DISTANCE_PCT]
count,4.195810e+06,4.195810e+06,4.195810e+06,4195810.0,4.195810e+06,4.195810e+06,4.195810e+06,4.195810e+06,4.195810e+06,4.195810e+06,...,4.195810e+06,4.195810e+06,4.195810e+06,4.195810e+06,4.195810e+06,4.195810e+06,4.195810e+06,4.195810e+06,4.195810e+06,4.195810e+06
mean,2.097904e+06,2.168731e+04,1.569672e+09,16.0,3.308608e+02,1.585241e+09,1.801955e+02,5.946907e-01,9.593181e-03,4.591260e-01,...,1.799110e+01,-3.951201e-01,-3.957872e+00,-6.541939e+00,-6.740557e-02,-6.092799e-01,2.580714e-01,2.737965e+02,4.668203e+01,1.426694e-01
std,1.211226e+06,1.744607e+04,1.149001e+08,0.0,1.057264e+02,1.150368e+08,2.117639e+02,3.225268e-01,1.446229e-02,8.408956e+00,...,2.975851e+01,3.328973e-01,4.086940e+03,6.570473e+01,4.962613e-01,1.160099e+00,2.094723e-01,2.851104e+03,5.310940e+01,1.463328e-01
min,0.000000e+00,0.000000e+00,1.262639e+09,16.0,1.022500e+02,1.263589e+09,0.000000e+00,0.000000e+00,-8.000000e-05,-2.815400e+03,...,0.000000e+00,-1.000000e+00,-6.645702e+06,-3.251200e+03,-7.833699e+01,-3.656880e+01,-5.000000e-04,0.000000e+00,0.000000e+00,0.000000e+00
25%,1.048952e+06,6.405000e+03,1.536782e+09,16.0,2.683400e+02,1.546290e+09,2.800000e+01,3.395200e-01,1.980000e-03,1.277100e-01,...,1.690000e+00,-6.759175e-01,1.900000e-03,1.043000e-01,-6.519000e-02,-6.822400e-01,1.620200e-01,0.000000e+00,1.070000e+01,3.600000e-02
50%,2.097904e+06,1.722300e+04,1.605215e+09,16.0,3.562500e+02,1.618430e+09,1.010000e+02,6.820300e-01,5.440000e-03,3.252100e-01,...,7.660000e+00,-3.148600e-01,5.460000e-03,3.091500e-01,-3.360000e-02,-1.815600e-01,2.224100e-01,6.000000e+00,2.720000e+01,9.100000e-02
75%,3.146857e+06,3.464400e+04,1.648757e+09,16.0,4.199900e+02,1.663963e+09,2.520000e+02,8.872700e-01,1.227000e-02,6.897500e-01,...,2.120000e+01,-8.668000e-02,1.218000e-02,6.770200e-01,-1.738000e-02,-3.474000e-02,3.031200e-01,7.100000e+01,6.220000e+01,2.030000e-01
max,4.195809e+06,7.156100e+04,1.703884e+09,16.0,4.777700e+02,1.797628e+09,1.096000e+03,1.000000e+00,2.577920e+00,1.473281e+02,...,1.205000e+03,0.000000e+00,2.525252e+02,8.774020e+01,0.000000e+00,0.000000e+00,2.411676e+01,3.557080e+05,4.444000e+02,1.250000e+00

In [5]:
data.head()

,Unnamed: 0,level_0,[QUOTE_UNIXTIME],[QUOTE_READTIME],[QUOTE_DATE],[QUOTE_TIME_HOURS],[UNDERLYING_LAST],[EXPIRE_DATE],[EXPIRE_UNIX],[DTE],...,[P_LAST],[P_DELTA],[P_GAMMA],[P_VEGA],[P_THETA],[P_RHO],[P_IV],[P_VOLUME],[STRIKE_DISTANCE],[STRIKE_DISTANCE_PCT]
0,0,0,1664827200,2022-10-03 16:00,2022-10-03,16.0,366.62,2022-10-03,1664827200,0.0,...,0.01,-0.00706,0.00519,0.00353,-0.00989,0.00000,0.24586,31198.0,9.6,0.026
1,1,1,1664827200,2022-10-03 16:00,2022-10-03,16.0,366.62,2022-10-03,1664827200,0.0,...,0.01,-0.00917,0.00725,0.00351,-0.00951,-0.00040,0.19937,27324.0,7.6,0.021
2,2,2,1664827200,2022-10-03 16:00,2022-10-03,16.0,366.62,2022-10-03,1664827200,0.0,...,0.01,-0.01010,0.00915,0.00476,-0.00978,-0.00016,0.17624,74485.0,6.6,0.018
3,3,3,1664827200,2022-10-03 16:00,2022-10-03,16.0,366.62,2022-10-03,1664827200,0.0,...,0.11,-0.24934,0.32698,0.05224,-0.14498,-0.00205,0.05915,69177.0,0.6,0.002
4,4,4,1664827200,2022-10-03 16:00,2022-10-03,16.0,366.62,2022-10-03,1664827200,0.0,...,0.62,-0.61709,0.33107,0.06284,-0.28478,-0.00447,0.07187,56928.0,0.4,0.001

In [9]:
print(data.columns)

Index(['Unnamed: 0', 'level_0', '[QUOTE_UNIXTIME]', '[QUOTE_READTIME]',
       '[QUOTE_DATE]', '[QUOTE_TIME_HOURS]', '[UNDERLYING_LAST]',
       '[EXPIRE_DATE]', '[EXPIRE_UNIX]', '[DTE]', '[C_DELTA]', '[C_GAMMA]',
       '[C_VEGA]', '[C_THETA]', '[C_RHO]', '[C_IV]', '[C_VOLUME]', '[C_LAST]',
       '[C_SIZE]', '[C_BID]', '[C_ASK]', '[STRIKE]', '[P_BID]', '[P_ASK]',
       '[P_SIZE]', '[P_LAST]', '[P_DELTA]', '[P_GAMMA]', '[P_VEGA]',
       '[P_THETA]', '[P_RHO]', '[P_IV]', '[P_VOLUME]', '[STRIKE_DISTANCE]',
       '[STRIKE_DISTANCE_PCT]'],
      dtype='object')

In [2]:
import json

with open("strings.json") as f:
    d = json.load(f)
    print(d)

SyntaxError: 'break' outside loop (3064426564.py, line 8)